//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _0000727_mayonez_400_ml_tat_65_330_grs_510 {
            get {
                object obj = ResourceManager.GetObject("0000727_mayonez-400-ml-tat-65-330-grs_510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _0590fb5bdf5c9ea15546c3393a43ef85_thumb {
            get {
                object obj = ResourceManager.GetObject("0590fb5bdf5c9ea15546c3393a43ef85_thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _11013027_0cace4_1650x1650 {
            get {
                object obj = ResourceManager.GetObject("11013027-0cace4-1650x1650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _13439_01 {
            get {
                object obj = ResourceManager.GetObject("13439_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _2000g_yogurt_yeni {
            get {
                object obj = ResourceManager.GetObject("2000g_yogurt_yeni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _30 {
            get {
                object obj = ResourceManager.GetObject("30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _430gr_Premium_Ketçap_copy {
            get {
                object obj = ResourceManager.GetObject("430gr-Premium-Ketçap-copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _500_ml_water_bottle_500x500_1 {
            get {
                object obj = ResourceManager.GetObject("500-ml-water-bottle-500x500-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _640px_Turkish_bread {
            get {
                object obj = ResourceManager.GetObject("640px-Turkish_bread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_nescafe_gold_jar_png_5a38c1200c6295_4744264615136688960507 {
            get {
                object obj = ResourceManager.GetObject("coffee-nescafe-gold-jar-png-5a38c1200c6295.4744264615136688960507", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap f8cd24c8_e7b5_45e3_ad30_996a0c8c4756 {
            get {
                object obj = ResourceManager.GetObject("f8cd24c8-e7b5-45e3-ad30-996a0c8c4756", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_carbonated_water_perrier_sparkling_water_mineral_w_natural_mineral_water_perrier_5baa55369495d8_0039773715378895906086 {
            get {
                object obj = ResourceManager.GetObject("kisspng-carbonated-water-perrier-sparkling-water-mineral-w-natural-mineral-water-" +
                        "perrier-5baa55369495d8.0039773715378895906086", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_lays_stax_potato_chip_french_fries_tortilla_chip_lays_potato_chips_5a753e619fb2d8_1063208815176331216541 {
            get {
                object obj = ResourceManager.GetObject("kisspng-lays-stax-potato-chip-french-fries-tortilla-chip-lays-potato-chips-5a753e" +
                        "619fb2d8.1063208815176331216541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_lettuce_sandwich_butterhead_lettuce_vegetable_sala_lettuce_5abb79e2ca0f80_4373410515222358748277 {
            get {
                object obj = ResourceManager.GetObject("kisspng-lettuce-sandwich-butterhead-lettuce-vegetable-sala-lettuce-5abb79e2ca0f80" +
                        ".4373410515222358748277", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_the_coca_cola_company_fizzy_drinks_diet_coke_coca_cola_5ad66696527516_0037022415240004063378 {
            get {
                object obj = ResourceManager.GetObject("kisspng-the-coca-cola-company-fizzy-drinks-diet-coke-coca-cola-5ad66696527516.003" +
                        "7022415240004063378", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap large_green_apple_png_clipart_5a3c4889f10d22_0851647615139001699874_1_ {
            get {
                object obj = ResourceManager.GetObject("large-green-apple-png-clipart-5a3c4889f10d22.0851647615139001699874(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_full_water_bottle {
            get {
                object obj = ResourceManager.GetObject("png-clipart-full-water-bottle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_potato_potato {
            get {
                object obj = ResourceManager.GetObject("png-clipart-potato-potato", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_bread_hand_painted_bread_european_breads_large_column_pakistan_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-bread-hand-painted-bread-european-breads-large-column-pakistan-th" +
                        "umbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_bread_hand_painted_bread_european_breads_large_column_pakistan_thumbnail1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-bread-hand-painted-bread-european-breads-large-column-pakistan-th" +
                        "umbnail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_bread_hand_painted_bread_european_breads_large_column_pakistan_thumbnail2 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-bread-hand-painted-bread-european-breads-large-column-pakistan-th" +
                        "umbnail2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_potato_chip_ruffles_doritos_lay_s_brand_chips_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-potato-chip-ruffles-doritos-lay-s-brand-chips-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_tomatoes_tomato_tomato_vegetables_tomatoes_clipart {
            get {
                object obj = ResourceManager.GetObject("png-transparent-tomatoes-tomato-tomato-vegetables-tomatoes-clipart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap resim_2022_12_09_163804889 {
            get {
                object obj = ResourceManager.GetObject("resim_2022-12-09_163804889", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap sarelle_kakaolu_findik_ezmesi_350_gr_e59c04_1650x1650 {
            get {
                object obj = ResourceManager.GetObject("sarelle-kakaolu-findik-ezmesi-350-gr-e59c04-1650x1650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
